### ISSUE TITLE
Please activate coveralls.io

### ISSUE THREAD

**Issue by Natim** [peopledoc/check_po#14]
https://coveralls.io/r/peopledoc/check_po?branch=master

**Comment by mgu** [comment]
Do you want to use Codecov.io instead of Coveralls.io ?

**Comment by Natim** [comment]
I don't know, I just realized that the badge wasn't working. I never used codecov.io

**Comment by mgu** [comment]
I don't want to add another tool to that can access our organization information (like teams) :)
